#!/bin/bash
#SBATCH --partition=C1Mitad1
#SBATCH --job-name=anxi13
#SBATCH --output=anxia13.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Tesis/Proyecto_tecnologico/New/Fuzzy_key_post
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python anxia13.py
date

