#!/bin/bash
#SBATCH --partition=C1Mitad1
#SBATCH --job-name=fuzzy_anxia9
#SBATCH --output=results_fuzzy_anxia9.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Proyecto_tecnologico/Fuzzy-Vectorization
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python fuzzy_anxia9.py
date
