#!/bin/bash
#SBATCH --partition=C1Mitad1
#SBATCH --job-name=sim_dep_model2
#SBATCH --output=results_sim_dep2.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Proyecto_tecnologico/Sim_Vec
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python sim_dep3.py
date
