#!/bin/bash
#SBATCH --partition=C1Mitad1
#SBATCH --job-name=key_anxia_model
#SBATCH --output=results_key_anxia1.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Proyecto_tecnologico/Sim_key
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python sim_anxia_key1.py
python sim_anxia_key2.py
date
