#!/bin/bash
#SBATCH --partition=C1Mitad1
#SBATCH --job-name=vectorization_dep
#SBATCH --output=results_vec_dep.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Proyecto_tecnologico/User_Vec
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python vec_dep.py
date
