#!/bin/bash
#SBATCH --partition=GPU
#SBATCH --job-name=train_model
#SBATCH --output=results_train.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Proyecto_tecnologico
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python train_model.py
date
