#!/bin/bash
#SBATCH --partition=C1Mitad1
#SBATCH --job-name=key_model10
#SBATCH --output=results_key_dep10.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Proyecto_tecnologico/Sim_key
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python sim_dep_key7.py
date


