#!/bin/bash
#SBATCH --partition=C1Mitad1
#SBATCH --job-name=bi_anxia_model
#SBATCH --output=results_bi_anxia.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Proyecto_tecnologico
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python bi_anxia.py
date
