#!/bin/bash
#SBATCH --partition=C1Mitad1
#SBATCH --job-name=sim_dep_model5
#SBATCH --output=results_sim_dep5.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Proyecto_tecnologico/Sim_Vec
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python sim_dep2_1.py
python sim_dep2_2.py
date

