#!/bin/bash
#SBATCH --partition=C1Mitad1
#SBATCH --job-name=concatenate_key
#SBATCH --output=con_key.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Proyecto_tecnologico/train_yake
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python con_keywords.py
date


