#!/bin/bash
#SBATCH --partition=GPU
#SBATCH --job-name=train_model
#SBATCH --output=train_yake_anxia.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Proyecto_tecnologico/train_yake
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python train_yake_anxia.py
date

