#!/bin/bash
#SBATCH --partition=C1Mitad1
#SBATCH --job-name=fuzzy_key_anxia2
#SBATCH --output=results_fka2.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Tesis/Proyecto_tecnologico/Fuzzy_Key
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python fuzzy_key_anxia3.py
python fuzzy_key_anxia4.py
date
            
