#!/bin/bash
#SBATCH --partition=C1Mitad1
#SBATCH --job-name=fuzzy_w_anxia3
#SBATCH --output=results_fwa3.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=maria.garcia@cimat.mx
cd /home/est_posgrado_maria.garcia/Proyecto_tecnologico/Fuzzy_key_w
source /opt/anaconda351/etc/profile.d/conda.sh
conda activate proyecto
hostname
date
python fuzzy_w_anxia5.py
date
